### PR TITLE
Two new Games: Fair Cake Cutting and Kuhn Poker

### PR DESCRIPTION
**Pull request by ankuromar296**
I have tried to implement two more games namely fair cake cutting game and kuhn poker game.. These are very basic implementation and needs a lot of modification to include more number of players. With the time given, more functionalities can be added to the module.

### CODE REVIEW

**Comment by drvinceknight** [comment]
I'm taking a look at this. Note that it has created a trac ticket: http://trac.sagemath.org/ticket/17999#comment:4

Usually Sage development is done via trac.

**Comment by drvinceknight** [comment]
I'm quite confused by this as you seem to have pasted in the diffs from a git commit? I'd suggest you take a look at this repository: https://github.com/theref/sage-game-theory

That is where the main development happens for Game Theory. In particular you might want to checkout and work from the [catalog](https://github.com/theref/sage-game-theory/tree/catalog) branch there. That branch is actively working on creating a catalog of games which seems to be where you got some of the code (I apologise if I'm confused). For example in [Kuhn_Poker](https://github.com/ankuromar296/sage/blob/master/src/sage/game_theory/Kuhn_Poker) I see:

```
diff --git a/src/sage/game_theory/named_games.py b/src/sage/game_theory/named_games.py
index b9da09e..d7d9958 100644
--- a/src/sage/game_theory/named_games.py
+++ b/src/sage/game_theory/named_games.py
@@ -11,3 +11,4 @@ from sage.game_theory.catalog import HawkDove
 from sage.game_theory.catalog import MatchingPennies
 from sage.game_theory.catalog import Pigs
 from sage.game_theory.catalog import PrisonersDilemma
+from sage.game_theory.catalog import RPS
```

**Comment by ankuromar296** [comment]
I apologise for my mistake. I will take care of it in future. I used existing codes from  https://github.com/sagemath/sage/tree/e88642d0ec3dc79278b8828a0b91e5d2d654d17a/src/sage/game_theory and took help from the existing tickets on game theory from http://trac.sagemath.org/wiki/TicketReports to start builiding upon. Fair cake cutting is a simple zero sum game and can be easily implemented by using existing source available. For kuhn poker, i have exhaustively defined every possible scenario for a two player game with 3 different cards with different payoffs.

**Comment by theref** [comment]
I suggest you have a read of the sage developers guide, there's a lot of useful information about general conventions for contributing. http://www.sagemath.org/doc/developer/

You've currently only included what looks like a diff file, reading through code that's already been included in Game Theory for Sage should help with structure.

It would be really good to get these included, looking forward to seeing how things progress!!

**Comment by kcrisman** [comment]
Given that this will depend on http://trac.sagemath.org/ticket/17392 pretty heavily, please continue all further discussion at http://trac.sagemath.org/ticket/17999.  @ankuromar296 please feel free to (http://doc.sagemath.org/html/en/developer/trac.html#obtaining-an-account)[get on Trac] if you haven't already.

**Comment by fchapoton** [comment]
This should be closed now, please.

**Pull request closed without merging**
