### PR TITLE
adding conversion for Product and Divide class in M2/Sage interface.

### PR DESCRIPTION
**Pull request by ZonovaX**

### CODE REVIEW

**Comment by paulmasson** [comment]
@Babyll Sage development doesn't happen on GitHub yet, but on https://trac.sagemath.org. If you want to contribute to Sage, you'll first need to open and account there and follow the documentation to set up Git for merging changes.

There also appears to be an open ticket (https://trac.sagemath.org/ticket/20936) with exactly the same changes as here. Are you already on Trac?

The parentheses in print() are intended to help move Sage from Python 2.7 to 3. The developer who went to the trouble to put them in would not be happy to see them all removed!

**Comment by ZonovaX** [comment]
I am on Trac! I'm very sorry if I di something incorrectly, I take it I
accidentally tried to push directly to github or something similar? I'm a
bit new with git and ran into some issues and was trying to update my copy
of the sage source to the latest development copy, and apparently I
accidentally caused some trouble. Again, I'm very sorry! Thanks for telling
me.

On Wed, Jul 6, 2016 at 7:22 PM, Paul Masson notifications@github.com
wrote:

> @Babyll https://github.com/Babyll Sage development doesn't happen on
> GitHub yet, but on https://trac.sagemath.org. If you want to contribute
> to Sage, you'll first need to open and account there and follow the
> documentation to set up Git for merging changes.
> 
> There also appears to be an open ticket (
> https://trac.sagemath.org/ticket/20936) with exactly the same changes as
> here. Are you already on Trac?
> 
> The parentheses in print() are intended to help move Sage from Python 2.7
> to 3. The developer who went to the trouble to put them in would not be
> happy to see them all removed!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/sagemath/sage/pull/61#issuecomment-230946046, or mute
> the thread
> https://github.com/notifications/unsubscribe/AMDSeCTdVK1dcQcOxkZ6EWzpXmxaYr6Fks5qTEbdgaJpZM4JGk0_
> .

## 

---

(__/) This is Bunny. Copy Bunny into
(O.o ) your signature to help him

## (> < ) on his way to world domination

**Comment by paulmasson** [comment]
Not a problem! Since you're the author of this pull request, please close it:

https://help.github.com/articles/closing-a-pull-request/

**Comment by ZonovaX** [comment]
Has it been closed? I no longer see it under my Pull Requests tab.

On Wed, Jul 6, 2016 at 9:12 PM, Paul Masson notifications@github.com
wrote:

> Not a problem! Since you're the author of this pull request, please close
> it:
> 
> https://help.github.com/articles/closing-a-pull-request/
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/sagemath/sage/pull/61#issuecomment-230960881, or mute
> the thread
> https://github.com/notifications/unsubscribe/AMDSeC5jtgnbzMm0aQbUwXecrjuJFxeDks5qTGB1gaJpZM4JGk0_
> .

## 

---

(__/) This is Bunny. Copy Bunny into
(O.o ) your signature to help him

## (> < ) on his way to world domination

**Comment by paulmasson** [comment]
All set. Thanks!

**Pull request closed without merging**
