### PR TITLE
Handle leading zeros correctly in significant figure computation.

### PR DESCRIPTION
**Pull request by robertwb**

### CODE REVIEW

**Comment by paulmasson** [comment]
This repository is a mirror of the Trac repository, which is where commits are still submitted. Please remove the branch you created and close this pull request. Thank!

**Comment by robertwb** [comment]
I moved the code to https://github.com/robertwb/sage/tree/real-prec and when I have time will follow the 22 steps to push this through Trac.

**Comment by robertwb** [comment]
https://github.com/robertwb/sage/commit/97f799fc2729119e013e78ee807879c857e8f01e fixes this issue mentioned at https://groups.google.com/forum/#!topic/sage-devel/KhaL5hX08uM

**Comment by paulmasson** [comment]
I'd be happy to submit the commit through Trac tomorrow and credit you as author if you'd like.

**Pull request closed without merging**
