### PR TITLE
Download-only option for upstream sources, checksum verification.

### PR DESCRIPTION
**Pull request by robertwb**

### CODE REVIEW

**Comment by kini** [comment]
This duplicates portage functionality and sage-on-gentoo data, doesn't it?

**Comment by robertwb** [comment]
Probably. Essentially all of the spkg stuff is redundant, right? I still think we need this sooner rather than later (e.g. for automated testing).

**Comment by kini** [comment]
Right, all the SPKG stuff is redundant, but it's also very simple right now. IMO it might be a waste of time to make the SPKG system appreciably more sophisticated than it currently is, if we're going to eventually switch to Portage. But I'm sure you know better than I do what's necessary to have ASAP and what can wait. Just thought I'd point out the duplication of effort :)

**Comment by robertwb** [comment]
Yes, we shouldn't invest too much into this. Keeping track of what code
we're actually building as part of the revision control is essential
(especially for trusting automated tools like the patchbot), so I think
this is necessary ASAP (I certainly don't want to be the release manager
without it).

**Comment by ohanar** [comment]
Seems like github's recent redesign deleted some of my line comments.

**Comment by robertwb** [comment]
The issue is probably that I force-pushed because many of the checksums (and, their respective tarballs) changed. I'll avoid that in the future, I didn't think I'd loose anything.

**Comment by robertwb** [comment]
Isn't $USE_LOCAL_SCRIPTS iff package-version.txt matches up?

**Comment by ohanar** [comment]
Yes, but it is only set in `sage-spkg`, so you still have to check in `sage-fix-spkg-checksums`.

**Comment by robertwb** [comment]
Ah, yes, good point. Done.

**Comment by ohanar** [comment]
Ok, I fixed a few small issues: c90ca0b63542e6891f50d9447e08ac16ce7a691c, otherwise everything looks good to me. If someone can checkoff on that commit, I'd be happy to give #329 a positive review and merge this in.

**Comment by robertwb** [comment]
Looks good to me.

**Comment by robertwb** [comment]
How to I fetch this commit?

**Comment by ohanar** [comment]
`git fetch git@github.com:ohanar/sage.git checksums`

**Comment by robertwb** [comment]
Ah, that's the branch it was sitting in. Done.

**Comment by robertwb** [comment]
Do you want to merge this?

**Comment by ohanar** [comment]
I have no issue merging this, but I would like to be on board with Jeroen.

**Pull request merged**
