### PR TITLE
[doc] Revise src/doc/en/tutorial/interactive_shell.rst

### PR DESCRIPTION
**Pull request by MaskRay**

### CODE REVIEW

**Comment by roed314** [comment]
Hi, thanks for the contribution!  We don't actually use github to do development (it's just a mirror that people can clone from).  To get this included into Sage, ask for an account at https://trac.sagemath.org/ (instructions for doing so are on the front page).  Then see http://doc.sagemath.org/html/en/developer/ for more details on how to setup keys, push changes to trac, etc.

**Comment by MaskRay** [comment]
Oh, sorry, I'll follow the guideline.

**Comment by roed314** [comment]
No problem!  It's very common for people to try to submit pull requests here.

**Comment by MaskRay** [comment]
Who should I set the "Reviewers:" to ?
https://trac.sagemath.org/ticket/22934

**Comment by kiwifb** [comment]
The person doing the code review should set that field. Your branch needs rebasing on the latest develop branch.

**Pull request closed without merging**
