### PR TITLE
Mode returns sorted list

### PR DESCRIPTION
**Pull request by Mianto**
stats.Mode now returns a sorted list to the inputs have same frequency.

### CODE REVIEW

**Comment by paulmasson** [comment]
@Mianto SageMath development happens on https://trac.sagemath.org/. The GitHub repository is a mirror of the Trac repository. If you'd like your improvements to be considered for addition to SageMath, then please request a Trac account and open a ticket with this commit.

**Comment by paulmasson** [comment]
@Mianto SageMath development happens on https://trac.sagemath.org/. The GitHub repository is a mirror of the Trac repository. If you'd like your improvements to be considered for addition to SageMath, then please request a Trac account and open a ticket with this commit.

**Comment by Mianto** [comment]
Actually I have sent mail to request a Trac account but it hasn't been activated.@paulmasson

**Comment by fchapoton** [comment]
see https://trac.sagemath.org/ticket/21668

**Comment by fchapoton** [comment]
This has been handled in  https://trac.sagemath.org/ticket/21668 and can now be closed.

**Pull request closed without merging**
